import React from 'react';
import { Link } from 'react-router-dom';

const TermsOfService = () => {
    return (
        <div className="min-h-screen w-full max-w-4xl mx-auto p-6 md:p-12 font-sans animate-fade-in">
            <div className="bg-white dark:bg-gray-800 p-8 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-700">
                <Link to="/" className="text-blue-600 dark:text-blue-400 hover:underline mb-8 inline-block font-semibold">
                    &larr; Back to Home
                </Link>
                
                <h1 className="text-3xl md:text-4xl font-extrabold mb-8 text-gray-900 dark:text-white">Terms and Conditions</h1>
                
                <div className="space-y-8 text-gray-700 dark:text-gray-300 leading-relaxed text-lg">
                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">1. Acceptance of Terms</h2>
                        <p>By accessing and using The Spanish Suite, you agree to be bound by these Terms and Conditions.</p>
                    </section>
                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">2. User Conduct</h2>
                        <p>You agree to use the platform for lawful educational purposes. Any misuse, abuse of the AI conversation tools, or attempt to compromise the platform's security will result in account termination.</p>
                    </section>
                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">3. Premium Subscriptions</h2>
                        <p>Certain features require a premium subscription. All payments are processed securely via third-party providers. We reserve the right to modify our pricing and subscription tiers.</p>
                    </section>
                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">4. Disclaimer of Warranties</h2>
                        <p>The service is provided "as is" without any warranties. We do not guarantee that the application will be error-free or uninterrupted.</p>
                    </section>
                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">5. AI Interactions</h2>
                        <p>The "Speak Companion" utilizes artificial intelligence to simulate conversations. We are not responsible for inaccurate translations or unexpected responses generated by the AI.</p>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default TermsOfService;
