import React from 'react';
import { Link } from 'react-router-dom';

const TermsOfService = () => {
    return (
        <div className="min-h-screen w-full max-w-4xl mx-auto p-6 md:p-12 font-sans animate-fade-in">
            <div className="bg-white dark:bg-gray-800 p-8 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-700">
                <Link to="/" className="text-blue-600 dark:text-blue-400 hover:underline mb-8 inline-block font-semibold">
                    &larr; Back to Home
                </Link>

                <h1 className="text-3xl md:text-4xl font-extrabold mb-8 text-gray-900 dark:text-white">Terms and Conditions</h1>

                <div className="space-y-8 text-gray-700 dark:text-gray-300 leading-relaxed text-lg">
                    <section>
                        <p className="text-sm text-gray-500 dark:text-gray-400">Last Updated: June 2026</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">1. Acceptance of Terms</h2>
                        <p>By accessing or using The Spanish Suite (the "Service"), you agree to be bound by these Terms and Conditions. If you do not agree, you must immediately cease using the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">2. Description of Service</h2>
                        <p>The Spanish Suite provides language learning tools including custom reading materials, a Spaced Repetition System (SRS) for flashcard study, and AI-driven conversation simulators (the "Speak Companion").</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">3. AI-Generated Content Disclaimer</h2>
                        <p>Our "Speak Companion" utilizes advanced artificial intelligence models. <strong>You acknowledge and agree that:</strong></p>
                        <ul className="list-disc pl-6 mt-2 space-y-2">
                            <li>AI outputs are generated programmatically and may occasionally be inaccurate, incorrect, incomplete, offensive, biased, or inappropriate.</li>
                            <li>We do not control the AI outputs and are not liable for any statements, translations, suggestions, or conversations generated by the AI.</li>
                            <li>The Service is for educational purposes only. You assume full responsibility for your interactions with the AI.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">4. Billing, Subscriptions, and Refund Policy</h2>
                        <p>Certain features require a premium subscription. All billing is processed securely through Stripe, our third-party payment provider.</p>
                        <ul className="list-disc pl-6 mt-2 space-y-2">
                            <li><strong>Recurring Billing:</strong> By subscribing, you authorize recurring monthly or annual charges to your payment method until you cancel.</li>
                            <li><strong>Cancellation:</strong> You may cancel your subscription at any time via your Account Settings dashboard. Cancellation will stop future renewals but will not result in a refund for the current billing cycle.</li>
                            <li><strong>No Refunds:</strong> Except as required by local law, all sales are final, and we do not offer refunds, credits, or prorated billing for partial subscription periods.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">5. Intellectual Property</h2>
                        <p>All content included in the Service, including stories, software, graphics, text, and features, is the intellectual property of The Spanish Suite or its licensors. You are granted a limited, non-transferable, and revocable license to access the content for personal, non-commercial learning only. You may not scrape, copy, or redistribute any materials from our database.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">6. User Content License</h2>
                        <p>By entering text, speech, or prompt inputs into our AI chat or SRS system, you grant us a worldwide, royalty-free, non-exclusive license to transmit, process, and use that content solely for the purpose of providing and improving the Service (e.g., transmitting inputs to AI endpoints to return your translation or response).</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">7. DISCLAIMER OF WARRANTIES</h2>
                        <p className="uppercase text-sm font-mono tracking-tight bg-gray-50 dark:bg-gray-900 p-4 rounded-xl border border-gray-100 dark:border-gray-800">
                            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, ACCURATE, OR ERROR-FREE, OR THAT AI RESPONSES WILL MEET YOUR EXPECTATIONS.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">8. LIMITATION OF LIABILITY</h2>
                        <p className="uppercase text-sm font-mono tracking-tight bg-gray-50 dark:bg-gray-900 p-4 rounded-xl border border-gray-100 dark:border-gray-800">
                            TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL THE SPANISH SUITE, ITS FOUNDERS, EMPLOYEES, OR PROVIDERS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, REVENUE, DATA, USE, GOODWILL, OR BUSINESS INTERRUPTION, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                        </p>
                        <p className="uppercase text-sm font-mono tracking-tight bg-gray-50 dark:bg-gray-900 p-4 rounded-xl border border-gray-100 dark:border-gray-800 mt-2">
                            OUR MAXIMUM AGGREGATE LIABILITY TO YOU FOR ANY AND ALL CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICE SHALL BE LIMITED TO THE TOTAL FEES ACTUALLY PAID BY YOU TO THE SERVICE IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO LIABILITY, <span className="font-extrabold text-xl"> OR FIFTY DOLLARS ($50), WHICHEVER IS GREATER.</span>
                        </p>
                        <p className="uppercase text-sm font-mono tracking-tight bg-gray-50 dark:bg-gray-900 p-4 rounded-xl border border-gray-100 dark:border-gray-800 mt-2">
                            THE LIMITATIONS SET FORTH IN THIS SECTION SHALL NOT APPLY TO: (I) DAMAGES CAUSED BY A PARTY'S GROSS NEGLIGENCE, WILLFUL MISCONDUCT, OR FRAUD; OR (II) CLAIMS ARISING UNDER INDEMNIFICATION OBLIGATIONS OR BREACHES OF APPLICABLE INTELLECTUAL PROPERTY RIGHTS.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">9. Governing Law</h2>
                        <p>These terms shall be governed by and construed in accordance with the laws of the State of Georgia / United States Of America, without regard to its conflict of law principles. Any dispute arising from these terms shall be subject to the exclusive jurisdiction of the courts located in Atlanta/Georgia/United States Of America.</p>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default TermsOfService;
